# Generated by Django 5.0.1 on 2024-02-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0002_customuser_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="suspension_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="suspension_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
