# Generated by Django 5.0.1 on 2024-02-24 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0003_customuser_suspension_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                ("account_description", models.TextField()),
                ("normal_side", models.CharField(max_length=255)),
                ("account_category", models.CharField(max_length=255)),
                ("account_subcategory", models.CharField(max_length=255)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("debit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_time_account_added", models.DateTimeField(auto_now_add=True)),
                ("order", models.CharField(max_length=255)),
                ("statement", models.CharField(max_length=255)),
                ("comment", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
