# Generated by Django 5.0.1 on 2024-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0004_chartofaccounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartofaccounts",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
