# Generated by Django 5.0.1 on 2024-03-03 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0006_alter_chartofaccounts_account_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoAEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("modified", "Modified"),
                            ("deactivated", "Deactivated"),
                        ],
                        max_length=11,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("before_change", models.JSONField(blank=True, null=True)),
                ("after_change", models.JSONField(blank=True, null=True)),
                (
                    "chart_of_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authenticate.chartofaccounts",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
