# Generated by Django 5.0.1 on 2024-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authenticate",
            "0008_errormessages_alter_chartofaccounts_account_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartofaccounts",
            name="normal_side",
            field=models.CharField(
                choices=[("Left", "Left"), ("Right", "Right")], max_length=255
            ),
        ),
    ]
