# Generated by Django 5.0.1 on 2024-03-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0009_alter_chartofaccounts_normal_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
