# Generated by Django 5.0.1 on 2024-03-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0010_journalentry_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="journal_entries/"),
        ),
    ]
