# Generated by Django 5.0.1 on 2024-04-13 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0011_journalentry_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="journalentry",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="authenticate.journalentrygroup",
            ),
        ),
    ]
