# Generated by Django 5.0.1 on 2024-04-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0012_journalentrygroup_journalentry_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="account_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
