# Generated by Django 5.0.1 on 2024-04-14 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0013_journalentry_account_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="account_category",
        ),
    ]
